### ISSUE TITLE
Torchscript version

### ISSUE THREAD

**Issue by xsacha** [lbin/Retinaface_Mobilenet_Pytorch#1]
Right now it is not possible to trace the model because of its reliance on _DCNv2.

> RuntimeError: 
> Could not export Python function call '_DCNv2'. Remove calls to Python functions before export. Did you forget add @script or @script_method annotation? If this is a nn.ModuleList, add it to __constants__:

**Comment by lbin** [comment]
Yes, you need to write a dcnv2 plugin for trace purpose
