### ISSUE TITLE
DCN in SSH modules

### ISSUE THREAD

**Issue by eeewhe** [lbin/Retinaface_Mobilenet_Pytorch#2]
Hi, is the improvement of test results on widerface due to deformable convolution in SSH modules?

**Comment by lbin** [comment]
ssh with dcn only should have 2%~3% improvement, we also add some train tricks.

**Comment by deep-practice** [comment]
About train tricks,can u give some hints?

**Comment by lbin** [comment]
@deep-practice trained more epoches
